## AlarmAnnotationEntityCollection
+ Include PagedItemCollection
+ items (array[AlarmAnnotationEntity], fixed-type) - The collection of annotations for an alarm

## AlarmAnnotationEntity
+ text (string) - The annotation text
+ user (string) - The user who annotated the alarm
+ creationTime:`2000-01-01T12:00:00Z` (string) - The dateTime for when the annotation on the alarm was created
+ action (AnnotationActionEnum) - The alarm action on which the annotation was created. In case if the annotation was not created during an alarm action, the default value will be "none"
+ alarmUrl:`https://{hostname}/api/v2/alarms/{id}` (string)  - A link to the alarm

## AuditAnnotationEntityCollection
+ Include PagedItemCollection
+ items (array[AuditAnnotationEntity], fixed-type) - The collection of audit annotations

## AuditAnnotationEntity
+ id:`00000000-0000-0000-0000-000000000000` (string) - The identifier of the audit annotation
+ auditUrl:`https://{hostname}/api/v2/audits/{id}` (string) - A link to the audit this audit annotation is attached to
+ creationTime:`2017-09-18T08:11:28Z` (string) - The dateTime representing the creation time when this audit annotation
+ user (string) - The user name of the user that initiated the audit annotation
+ text (string) - The text of the audit annotation
+ signature (Signature) - The user who created this audit annotation
+ action (AnnotationActionEnum) - The action on which the annotation was created. In case if the annotation was not created during an action, the default value will be "none"

## AnnotationActionEnum (enum)
+ 'none' - Indicates an annotation that was added as part of non AnnotationActionEnum action
+ 'acknowledged' - Indicates an annotation that was added as part of a acknowledged action
+ 'completed' - Indicates an annotation that was added as part of a completed action
+ 'discarded' - Indicates an annotation that was added as part of a discarded action
+ 'snoozed' - Indicates an annotation that was added as part of a snooze action