## AlarmEntityDigital
+ Include AlarmEntity
+ triggerValue (DigitalValueAlarm)- The digital value of the attribute of the object on which the alarm was triggered

## AlarmEntityAnalog
+ Include AlarmEntity
+ triggerValue (AnalogValueAlarm)- The analog value of the attribute of the object on which the alarm was triggered

## AlarmEntity
+ Include BaseObject
+ message (string) - The alarm message
+ isAckRequired (boolean) - Indicates whether an acknowledgment is required on the alarm
+ typeUrl:`https://{hostname}/api/v2/enumSets/{id}/members/{memberId}` (string) - A link to the enum member for the type of alarm
+ priority (number) - The priority of the alarm
+ creationTime:`2000-01-01T12:00:00Z` (string) - The dateTime for when the alarm was detected
+ isAcknowledged (boolean) - Indicates whether the alarm has been acknowledged
+ isDiscarded (boolean) - Indicates whether the alarm has been discarded
+ categoryUrl:`https://{hostname}/api/v2/enumSets/{id}/members/{memberId}` (string) - A link to the authorization category of the object when the alarm was generated
+ objectUrl:`https://{hostname}/api/v2/objects/{id}` (string) - A link to the object from which this alarm was generated
+ annotationsUrl:`https://{hostname}/api/v2/alarms/{id}/annotations` (string) - A link to the annotations available on the alarm
+ self:`https://{hostname}/api/v2/alarms/{id}` (string) - A link to this collection of alarms

## AlarmEntityCollection
+ Include PagedItemCollection
+ items (array) - The collection of alarms
    - (AlarmEntityAnalog)
    - (AlarmEntityDigital)

## AnalogValueAlarm
+ value:`68.9` (number) - The value of the attribute of the object on which the alarm was triggered
+ unitsUrl:`https://{hostname}/api/v2/enumSets/{id}/members/{memberId}` (string) - A link to the units of the object on which the alarm was triggered

## DigitalValueAlarm
+ value:`1` (number) - The value of the attribute of the object on which the alarm was triggered
+ valueEnumMemberUrl:`https://{hostname}/api/v2/enumSets/{id}/members/{memberId}` (string) - A link to the enum member for the alarm trigger value

## NetworkDeviceAlarmsRelationshipLinks
+ self:`https://{hostname}/api/v2/networkDevices/{id}/alarms` (string) - A link to this collection of network device alarms
+ networkDeviceUrl:`https://{hostname}/api/v2/networkDevices/{id}` (string) - A link to the network device from which this alarm was generated

## NetworkDeviceAlarmRelationshipLinks
+ self:`https://{hostname}/api/v2/networkDevices/{id}/alarms/{alarmId}` (string) - A link to this network device alarm
+ networkDeviceUrl:`https://{hostname}/api/v2/networkDevices/{id}` (string) - A link to the network device from which this alarm was generated

## NetworkDeviceAlarmEntity
+ Include AlarmEntity
+ Include NetworkDeviceAlarmRelationshipLinks

## NetworkDeviceAlarmsEntity
+ Include AlarmEntityCollection
+ Include NetworkDeviceAlarmsRelationshipLinks

## ObjectAlarmsRelationshipLinks
+ self:`https://{hostname}/api/v2/objects/{id}/alarms` (string) - A link to this collection of object alarms
+ objectUrl:`https://{hostname}/api/v2/objects/{id}` (string) - A link to the object from which which this alarm was generated

## ObjectAlarmRelationshipLinks
+ self:`https://{hostname}/api/v2/objects/{id}/alarms/{alarmId}` (string) - A link to this object alarm
+ objectUrl:`https://{hostname}/api/v2/objects/{id}` (string) - A link to the object from which this alarm was generated

## ObjectAlarmEntity
+ Include AlarmEntity
+ Include ObjectAlarmRelationshipLinks

## ObjectAlarmsEntity
+ Include AlarmEntityCollection
+ Include ObjectAlarmsRelationshipLinks