## SpaceLinkCollection
+ Include PagedItemCollection
+ items:`[/spaces/{id}]` (array[string], fixed-type) - The collection of space links

## SpaceEntity
+ Include SpaceData
+ Include SpaceRelationshipLinks

## SpaceEntityCollection
+ Include PagedItemCollection
+ items (array[SpaceEntity], fixed-type) - The collection of spaces

## SpaceData
+ Include BaseObject
+ name (string) - The name of the space
+ type:`/enumSets/{id}/members/{memberId}` (string) - A link to the type of space

## SpaceRelationshipLinks
+ self:`/spaces/{id}` (string) - A link to this space
+ parent:`/spaces/{id}` (string) - A link to the space that contains this space
+ spaces:`/spaces/{id}/spaces` (string) - A link to the spaces contained within this space
+ equipment:`/spaces/{id}/equipment` (string) - A link to the equipment instances serving this space
+ networkDevices:`/spaces/{id}/networkDevices` (string) - A link to the network devices serving this space