## NetworkDeviceLinkCollection
+ Include PagedItemCollection
+ items:`/networkDevices/{id}` (array[string], fixed-type) - The collection of network device links

## NetworkDeviceEntity
+ Include NetworkDeviceData
+ Include NetworkDeviceRelationshipLinks

## NetworkDeviceEntityCollection
+ Include PagedItemCollection
+ items (array[NetworkDeviceEntity], fixed-type) - The collection of network devices

## NetworkDeviceData
+ Include BaseObject
+ name (string) - The name of the network device
+ type:`/enumSets/{id}/members/{memberId}` (string) - A link to the type of network device
+ description (string) - The description for the network device
+ firmwareVersion:`10.0.0` (string) - The firmware version for the network device
+ category:`/enumSets/{id}/members/{memberId}` (string) - A link to the authorization category for the network device
+ timeZone:`/enumSets/{id}/members/{memberId}` (string) - A link to the time zone in which the device is located
+ ipAddress:`127.0.0.1` (string) - The IP address of the engine.
+ certificateExpirationDate:`2018-07-30T20:59:59.999Z` (string) - The expiration date of the certificate on the device.

## NetworkDeviceRelationshipLinks
+ self:`/networkDevices/{id}` (string) - The link to the network device
+ parent:`/networkDevices/{id}` (string) - A link to the network device that is the parent of this network device
+ networkDevices:`/networkDevices/{id}/networkDevices` (string) - A link to the network devices that are children of this network device
+ equipment:`/networkDevices/{id}/equipment` (string) - A link to the equipment instances hosted by this network device
+ spaces:`/networkDevices/{id}/spaces` (string) - A link to the spaces that are served by this network device
+ objects:`/networkDevices/{id}/objects` (string) - A link to the objects contained within this network device
+ attributes:`/networkDevices/{id}/attributes` (string) - A link to the attributes on this network device for which samples are available
+ alarms:`/networkDevices/{id}/alarms` (string) - A link to the alarms available for this network device