## Signature
+ fullName:`John Smith` (string) - The name of the person "signing"
+ reason (string) - The reason for signing

## LoginRequest
+ username: `johndoe` (string, required) - The user name of a Metasys account.
+ password: `ajdk2!xyp` (string, required) - The corresponding password of a Metasys account.

## LoginResponse
+ accessToken: `eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IklFa3FIW...` (string) - The access token for this session.
+ expires: `2018-08-03T18:23:45Z` (string) - The time at which the token will expire.