Group Enumerations
==================

This section contains information about enumeration-related resources as used within the Metasys API.

### Get Enum Sets [GET /enumSets{?page,pageSize}]
Retrieves a collection of all enumeration sets in the system.

+ Parameters
    + page (number, optional) - The page number of items to return
        + Default: `1`
    + pageSize (number, optional) - The maximum number of items to return in the response. Valid range is 1-1,000.
        + Default: `100`

+ Request
    + Headers

            Accept: application/vnd.metasysapi.v2+json
            Authorization: Bearer [token]

+ Response 200 (application/vnd.metasysapi.v2+json)
    + Headers

    + Attributes
        + Include EnumSetCollection
        + self:`https://{hostname}/api/v2/enumSets{?queryParams}` (string) - A link to this enum set collection

### Get A Single Enum Set [GET /enumSets/{id}]
Retrieves the specified enumeration set.

+ Parameters
    + id (number) - The identifier for the enum set

+ Request
    + Headers

            Accept: application/vnd.metasysapi.v2+json
            Authorization: Bearer [token]

+ Response 200 (application/vnd.metasysapi.v2+json)
    + Headers

    + Attributes(EnumSet)

### Get Enum Members [GET /enumSets/{id}/members{?page,pageSize}]
Retrieves the collection of member values belonging to the specified enumeration set.

+ Parameters
    + id (number) - The identifier for the enum set
    + page (number, optional) - The page number of items to return
        + Default: `1`
    + pageSize (number, optional) - The maximum number of items to return in the response. Valid range is 1-1,000.
        + Default: `100`

+ Request
    + Headers

            Accept: application/vnd.metasysapi.v2+json
            Authorization: Bearer [token]

+ Response 200 (application/vnd.metasysapi.v2+json)
    + Headers

    + Attributes
        + Include EnumMemberCollection
        + self:`https://{hostname}/api/v2/enumSets/{id}/members{?queryParams}` (string) - A link to this enum member collection

### Get A Single Enum Member [GET /enumSets/{id}/members/{memberId}]
Retrieves the specified enumeration member value.

+ Parameters
    + id (number) - The identifier for the enum set
    + memberId (number) - The identifier for the enum member

+ Request
    + Headers

            Accept: application/vnd.metasysapi.v2+json
            Authorization: Bearer [token]

+ Response 200 (application/vnd.metasysapi.v2+json)
    + Headers

    + Attributes(EnumMember)