# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Build
          command: |
            npm run build
            # if [ -n "$CIRCLE_PR_NUMBER" ]; then node build.js; fi
            # if [ -z "$CIRCLE_PR_NUMBER" ]; then node build.js && npm run publish; fi
            npm run lint
            npm run build:postman
            npm run preview
            npm run aglio

      # collect artifacts
      - store_artifacts:
          path: build/
          destination: api
