## DescriptionEnums
+ items (array[DescriptionEnum], fixed-type) - The list of returned enums and their counts.

## DescriptionEnum
+ intervalStartTime: `2018-07-30T20:00:00Z` (string) - The start time of the time interval.
+ intervalEndTime: `2018-07-30T20:59:59.999Z` (string) - The end time of the time interval.
+ auditCounts (array[DescriptionEnumCount], fixed-type)

## DescriptionEnumCount
+ id:`42` (number) - The enum id that corresponds to the user audit.
+ count:`15` (number) - The count of audits over the time interval.

## EngineList
+ policyViolationCounts (EnginePolicyVioloationCountsAndSeveritys)

## EnginePolicyVioloationCountsAndSeveritys
+ pre52 (CountAndSeverityLevel) - Count of engines with software version less than 5.2.
+ post52pre81 (CountAndSeverityLevel) - Count of engines with software version greater than or equal to 5.2 and less than 8.1.
+ post81 (CountAndSeverityLevel) - Count of engines with software version greater than or equal to 8.1.
+ expiringCerts (CountAndSeverityLevel) - Count of engines with a certificate expiring within 30 days.
+ expiredCerts (CountAndSeverityLevel) - Count of engines with a certificate that is expired.