## NotifierType (enum[string])
+ `email` - email
+ `snmp` - snmp
+ `syslog` - syslog
+ `printer` - printer

## EmailAuthenticationType (enum[string])
+ `none` - none
+ `smtp` - smtp
+ `popBeforeSmtp` - pop before smtp

## NotifierFilterPropertyName (enum[string])
+ `currentStatus` - Current Status
+ `priority` - Priority
+ `authorizationCategory` - Authorization Category
+ `acknowledgeRequired` - Acknowledge Required
+ `previousStatus` - Previous Status
+ `startDayOfWeek` - Start Day Of Week
+ `startTime` - Start Time
+ `endDayOfWeek` - End Day Of Week
+ `endTime` - End Time

## NotifierFilterPropertyNameForServer (enum[string])
+ `currentStatus` - Current Status
+ `priority` - Priority
+ `authorizationCategory` - Authorization Category
+ `acknowledgeRequired` - Acknowledge Required
+ `previousStatus` - Previous Status
+ `startDayOfWeek` - Start Day Of Week
+ `startTime` - Start Time
+ `endDayOfWeek` - End Day Of Week
+ `endTime` - End Time
+ `spaces` - Spaces
+ `equipment` - Equipment

## NotifierDestinationPriority (enum[string])
+ `high` - High
+ `normal` - Normal
+ `low` - Low

## NotifierFilterOperatorType (enum[string])
+ `==` - Equals To
+ `!=` - Not Equals To
+ `<`  - Less Than
+ `<=` - Less Than Equals To
+ `>`  - Greater Than
+ `>=` - Greater Than Equals To

## NotifierEnabled (enum[string])
+ `true` - True
+ `false` - False

## NotifierEntity
+ type: `email` (NotifierType) - The type of the notifier
+ label:`Email` (string) - The localized label of the notifier
+ configurationUrl:`/notifiers/email/configuration` (string) - A link to the notifier's configuration 
+ destinationUrl:`/notifiers/email/destinations` (string) - A link to the notifier's destinations
+ readOnly:`true` (boolean) - Indicates whether the user just has read only permission on the notifier

## EmailNotifierConfigurationEntity
+ type: `email` (NotifierType) - The type of the notifier
+ label:`Email` (string) - The localized label of the notifier
+ configuration (EmailNotifierConfiguration) - The email notifier configuration details

## EmailNotifierConfiguration
+ sslEmailEnabled (boolean) - Indicates whether SSL is enabled on Email. This is only used if the device's version is above 4.0
+ sslEmailIgnoreErrors (boolean) - Indicates whether ignoring SSL errors is enabled.This is only used if the device's version is above 4.0
+ authenticationType: `smtp` (EmailAuthenticationType) - The authentication mechanism to use
+ fromEmailAddress: `metasys@jci.com` (string) - The sender's email address
+ smtpHostname: `smtp.jci.com` (string) - The SMTP server host name. This is only used in case the authentication type is smtp or popBeforeSmtp
+ smtpPort:`25` (number) - The SMTP server port number. This is only used in case the authentication type is smtp or popBeforeSmtp
+ popConfigurationDetails (popConfiguration) - The POP Configuration
+ smtpConfigurationDetails (smtpConfiguration) - The SMTP Configuration
+ emailDiagnostics (string) - The email diagnostics information 

## popConfiguration
+ hostname: `pop.jci.com` (string, optional) - The POP server host-name
+ username: `sample@jci.com` (string, optional) - The POP server user name

## smtpConfiguration 
+ username: `sample@jci.com` (string, optional) - The SMTP server user name

## UpdateEmailNotifierConfiguration
+ sslEmailEnabled (boolean, optional) - Indicates whether SSL is enabled on Email. This is only used if the device's version is above 4.0
+ sslEmailIgnoreErrors: (boolean, optional) - Indicates whether ignoring SSL errors is enabled.This is only used if the device's version is above 4.0
+ authenticationType: `popBeforeSmtp` (EmailAuthenticationType) - The authentication mechanism to use
+ fromEmailAddress: `metasys@jci.com` (string) - The sender's email address
+ smtpHostname: `smtp.jci.com` (string) - The SMTP server host name
+ smtpPort:`25` (number) - The SMTP server port number
+ popConfigurationDetails (popConfigurationDetail) - The POP Configuration
+ smtpConfigurationDetails (smtpConfigurationDetail) - The SMTP Configuration

## popConfigurationDetail
+ Include popConfiguration
+ password: `password` (string, optional) - The POP server password

## smtpConfigurationDetail
+ Include smtpConfiguration
+ password: `password` (string, optional) - The SMTP server password

## NotifierPropertyCommonConstraint
+ label: `label` (string) - The name of the property
+ required (boolean) - Indicates whether property is mandatory while saving the configuration
+ readOnly (boolean) - Indicates whether property is editable

## NotifierEnumConstraint
+ Include NotifierPropertyCommonConstraint
+ type: `enum` (string) - The type of property
+ defaultValue (string) - The default value of property
+ set (array[string]) - The properties options available

## EnabledEnumConstraint
+ Include NotifierPropertyCommonConstraint
+ type: `enum` (string) - The type of property
+ defaultValue (string) - The default value of property
+ set (NotifierEnabled) - The properties options available

# PriorityEnumConstraint
+ Include NotifierPropertyCommonConstraint
+ type: `enum` (string) - The type of property
+ defaultValue (string) - The default value of property
+ set (NotifierDestinationPriority) - The properties options available

## NotifierStringConstraint
+ Include NotifierPropertyCommonConstraint
+ type: `enum` (string) - The type of property
+ defaultValue (string) - The default value of property
+ maxLength (number) - The max length of property

## NotifierNumberConstraint
+ Include NotifierPropertyCommonConstraint
+ type: `number` (string) - The type of property
+ defaultValue (number) - The default value of property
+ precision (number) - The precision value of property
+ minimum (number) - The minimum value of property
+ maximum (number) - The maximum value of property

## NotifierBitsPropertyConstraint
+ label (string) - The localized label of the notifier destination format property item
+ defaultValue (boolean) - The default value of notifier destination property item

## NotifierStringArrayConstraint
+ Of
    + type (string) - The data type of item
    + maxlength (number) - The max length of property
+ Include NotifierPropertyCommonConstraint
+ type: `array` (string) - The type of property
+ defaultValue (string) - The default value constraint of property

## NotifierDestinationFormatConstraint
+ Include NotifierPropertyCommonConstraint
+ type: `bits` (string) - The type of property
+ priority (NotifierBitsPropertyConstraint) - The priority format property constraint
+ message (NotifierBitsPropertyConstraint) - The message format property constraint
+ value (NotifierBitsPropertyConstraint) - The value format property constraint
+ siteName (NotifierBitsPropertyConstraint) - The site name format property constraint
+ itemDescription (NotifierBitsPropertyConstraint) - The item description format property constraint
+ itemFullyQualifiedReference (NotifierBitsPropertyConstraint) - The item fully qualified reference format property constraint
+ itemCategory (NotifierBitsPropertyConstraint) - The item category format property constraint
+ acknowledgeRequired (NotifierBitsPropertyConstraint) - The acknowledged required format property constraint
+ previousStatus (NotifierBitsPropertyConstraint) - The previous status format property constraint

## EventFilterConstraints
+ label (string) - The label of event filter
+ type (string) - The data type of event filter item
+ operator (NotifierFilterOperatorType) - The operation to use for filtering
+ values (NotifierStringArrayConstraint) - The value property of event filter item
+ required (boolean) -  Indicates whether a value is required corresponding to the filter

## EventFilterNumericPropertyConstraints
+ Include EventFilterConstraints
+ minimum 0 (number) - The minimum value
+ maximum 255 (number) - The maximum value

## NotifierEventFilterArrayConstraint
+ Of
    + type:`filter` (string) - The type of notifier filter
    + set - A set is composed of  property name, operator, value constraints
        + currentStatus
            + Include EventFilterConstraints
        + priority
            + Include EventFilterNumericPropertyConstraints
        + authorizationCategory
            + Include EventFilterConstraints
        + acknowledgeRequired
            + Include EventFilterConstraints
        + previousStatus
            + Include EventFilterConstraints
        + startDayOfWeek
            + Include EventFilterConstraints
        + startTime
            + Include EventFilterConstraints
        + endDayOfWeek
            + Include EventFilterConstraints
        + endTime
            + Include EventFilterConstraints
+ Include NotifierPropertyCommonConstraint
+ type: `array` (string) - The type of property
+ defaultValue (string) - The default value constraint of property

## NotifierEventFilterArrayConstraintForServer
+ Of
    + type:`filter` (string) - The type of notifier filter
    + set - A set is composed of  property name, operator, value constraints
        + currentStatus
            + Include EventFilterConstraints
        + priority
            + Include EventFilterNumericPropertyConstraints
        + authorizationCategory
            + Include EventFilterConstraints
        + acknowledgeRequired
            + Include EventFilterConstraints
        + previousStatus
            + Include EventFilterConstraints
        + startDayOfWeek
            + Include EventFilterConstraints
        + startTime
            + Include EventFilterConstraints
        + endDayOfWeek
            + Include EventFilterConstraints
        + endTime
            + Include EventFilterConstraints
        + spaces
            + Include EventFilterConstraints
        + equipment
            + Include EventFilterConstraints
+ Include NotifierPropertyCommonConstraint
+ type: `array` (string) - The type of property
+ defaultValue (string) - The default value constraint of property

## popConfigurationDetailConstraint
+ hostname (NotifierStringConstraint) - The POP host-name constraints
+ password (NotifierStringConstraint) - The POP password constraints
+ username (NotifierStringConstraint) - The POP user name constraints 

## smtpConfigurationDetailConstraint
+ password (NotifierStringConstraint) - The SMTP password constraints
+ username (NotifierStringConstraint) - The SMTP user name constraints

## EmailNotifierConfigurationConstraint
+ type:`email` (NotifierType) - The type of notifier
+ configuration (EmailConfigurationConstraint) -  The configuration constraints of email notifier

## EmailConfigurationConstraint
+ sslEmailEnabled (NotifierEnumConstraint, optional) - The SSL email enabled property constraints
+ sslEmailIgnoreErrors (NotifierEnumConstraint, optional) - The SSL Ignore email errors constraints
+ authenticationType (NotifierEnumConstraint) - The authentication mechanism constraints
+ fromEmailAddress (NotifierStringConstraint) - The sender's email address constraints
+ smtpHostname (NotifierStringConstraint) - The SMTP server host name constraints
+ smtpPort (NotifierNumberConstraint) - The SMTP server port number constraints
+ popConfigurationDetails (popConfigurationDetailConstraint) - The POP Configuration constraints
+ smtpConfigurationDetails (smtpConfigurationDetailConstraint) - The SMTP Configuration constraints

## BaseNotifierDestinationContainer
+ type: (NotifierType) - The type of the notifier
+ label:`Email` (string) - The localized label of the notifier

## EmailNotifierDestinationContainerForServer
+ Include BaseNotifierDestinationContainer
+ destinations (array[EmailNotifierDestinationForServer]) - The collection of email destinations

## EmailNotifierDestinationForServer
+ id:`6a00fbfa-fa27-5308-a927-b7405490259b` (string) - The unique identifier of the destination
+ label:`Destination 1` (string) - The localized label of the notifier destination
+ toEmailAddresses:["destination1@jci.com"] (array[string]) - The email address of one or more recipients
+ priority: (NotifierDestinationPriority) - The priority of the outbound email message
+ subject (string) - The user-defined text that appears in the subject field of the email message
+ retries (number) - The number or attempts made to send a message if there is a failure before the system discards it
+ enabled (boolean) - Indicates whether or not the destination is enabled
+ readOnly:`true` (boolean) - Indicates whether the user just has read only permission on the destination
+ eventFilter (array[NotifierDestinationEventFilterForServer]) - The rules to filter alarms
+ format (NotifierDestinationFormats) - Defines the format of the message, indicating which fields are present in the received message
+ escalationConfiguration (EscalationConfiguration) - The escalation settings for destination

## NewEmailNotifierDestinationForServer
+ label:`Destination 1` (string) - The localized label of the notifier destination
+ toEmailAddresses:["destination1@jci.com"] (array[string]) - The email address of one or more recipients
+ priority: (NotifierDestinationPriority) - The priority of the outbound email message
+ subject (string) - The user-defined text that appears in the subject field of the email message
+ retries (number) - The number or attempts made to send a message if there is a failure before the system discards it
+ enabled (boolean) - Indicates whether or not the destination is enabled
+ eventFilter (array[AddNotifierDestinationEventFilterForServer]) - The rules to filter alarms
+ format (NotifierDestinationFormats) - Defines the format of the message, indicating which fields are present in the received message
+ escalationConfiguration (EscalationConfiguration) - The escalation settings for destination

# EscalationConfiguration
+ emailRecipients: ["manager@jci.com"] (array[string]) - The email address of one or more recipients for alarm escalation 
+ delayInterval (EscalationDelay) - Total delay in an escalation of an alarm

## EscalationDelay
+ hours (number) - Delay in hours for alarm escalation
+ minutes (number) - Delay in minutes for alarm escalation

## NotifierDestinationFormats
+ priority (boolean) - Indicates whether destination delivery format contains a priority value
+ message (boolean) - Indicates whether destination delivery format contains a message value
+ value (boolean) - Indicates whether destination delivery format contains a value
+ siteName (boolean) - Indicates whether destination delivery format contains a site name value
+ itemDescription (boolean) - Indicates whether destination delivery format contains a item description value
+ itemFullyQualifiedReference (boolean) - Indicates whether destination delivery format contains a fully qualified reference value
+ itemCategory (boolean) - Indicates whether destination delivery format contains a item category value
+ acknowledgeRequired (boolean) -Indicates whether destination delivery format contains a acknowledge required value
+ previousStatus (boolean) - Indicates whether destination delivery format contains a previous status value

## DestinationSaveSuccessful 
+ destinationId:`f391d369-7eaa-5deb-8d1d-fb6697d679fc` (string) - The unique identification of created destination
+ url:`/notifiers/email/destinations` (string) - URL to get all the destinations

## AddNotifierDestinationEventFilterForServer
+ property: (NotifierFilterPropertyNameForServer) - The name of the property on an activity (alarm or audit) to filter on
+ operator: (NotifierFilterOperatorType) - The operation to use for filtering
+ values (array[string]) - The list of values

## AddNotifierDestinationEventFilter
+ property: (NotifierFilterPropertyName) - The name of the property on an activity (alarm or audit) to filter on
+ operator: (NotifierFilterOperatorType) - The operation to use for filtering
+ values (array[string]) - The list of values

## NotifierDestinationEventFilterForServer
+ property: (NotifierFilterPropertyNameForServer) - The name of the property on an activity (alarm or audit) to filter on
+ operator: (NotifierFilterOperatorType) - The operation to use for filtering
+ values (array[FilterValue]) - The list of values

## NotifierDestinationEventFilter
+ property: (NotifierFilterPropertyName) - The name of the property on an activity (alarm or audit) to filter on
+ operator: (NotifierFilterOperatorType) - The operation to use for filtering
+ values (array[FilterValue]) - The list of values

## FilterValue
+ value:`Normal` (string) - The value to use as the operand in the filter
+ name: `Building 1` (string) - The name of the space or equipment
+ isAuthorized (boolean) - Indicates weather user is authorized to view space or equipment
+ isDeleted (boolean) - Indicates weather space or equipment is deleted

## EscalationConfigurationConstraints
+ Include NotifierPropertyCommonConstraint
+ emailRecipients (NotifierStringArrayConstraint) - The constraints for the email address of one or more recipients for alarm escalation 
+ delayInterval (EscalationDelayConstraints) - The constraints for the total delay in an escalation of an alarm

## EscalationDelayConstraints
+ Include NotifierPropertyCommonConstraint
+ hours (NotifierNumberConstraint) - The constraints for the delay in hours for alarm escalation
+ minutes (NotifierNumberConstraint) - The constraints for the delay in minutes for alarm escalation

##EmailNotifierDestinationConstraintForServer
+ label (NotifierStringConstraint) - The constraints for the localized label of the notifier destination
+ toEmailAddresses (NotifierStringArrayConstraint) - The constraints for the email address of one or more recipients
+ priority (PriorityEnumConstraint) - The constraints for the priority of the outbound email message
+ subject (NotifierStringConstraint) - The user-defined text that appears in the subject field of the email message constraints
+ retries (NotifierNumberConstraint) - The constraints for the number of attempts made to send a message if there is a failure before the system discards it
+ enabled (EnabledEnumConstraint) - The constraints for the property which indicates whether the destination is enabled
+ eventFilters (NotifierEventFilterArrayConstraintForServer) - The constraints for the rules to filter alarms
+ format (NotifierDestinationFormatConstraint) - The constraints for format which defines the format of the message, indicating which fields are present in the received message
+ escalationConfiguration (EscalationConfigurationConstraints) - The constraints for the escalation settings for destination

