Group Users
============

This section contains information about user-related resources as used within the Metasys API.

### User Counts Report [GET /users/reports/counts]
Retrieves user counts report information.

+ Request
    + Headers

            Authorization: Bearer [token]

+ Response 200 (application/vnd.metasysapi.v2+json)
    + Headers

    + Attributes
        + Include UserStatisticsCollection